#!/bin/sh

set -eu

exec 2>&1

SERVICE_DIR="$( cd "$(dirname $0)" && echo ${PWD} )"
SERVICE_NAME="${SERVICE_DIR##*/}"
DEVICE="${SERVICE_NAME##*@}"

while [ ! -e "/dev/$DEVICE" ]
do
	echo "Waiting for ${DEVICE}..."
	sleep 5
done

echo "Starting getty for ${DEVICE}"

exec /sbin/getty -L "/dev/${DEVICE}" 115200 vt100
